services:
  - type: web
    name: job-agentic-ai
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5050
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_HEADLESS
        value: "true"
      - key: GROQ_API_KEY
        sync: false
      - key: ADZUNA_APP_ID
        sync: false
      - key: ADZUNA_APP_KEY
        sync: false
      - key: ADZUNA_COUNTRY
        value: in
